version: '3.8'
services:
  web:
    build: 
      context: .
      args:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #command: sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/kotonoha_drink
      - node_modules:/kotonoha_drink/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data 

volumes:
  db-store:
  node_modules: