# fly.toml app configuration file generated for kotonoha-drink on 2023-12-25T14:42:58+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kotonoha-drink"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
