# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Drink.create(name: 'コーヒー',word: '覚醒と洗練' , info: 'コーヒーは焙煎されたコーヒー豆から作られる飲み物で、世界中で愛されています。エネルギーと集中力を与える効果があります。', image:File.open('app/assets/images/0_0.png'), category: 0, display_order: 0)
Drink.create(name: 'カプチーノ', word: '心地よい朝の始まり', info: 'エスプレッソにスチームミルクとミルクフォームを加えたイタリア発祥のコーヒー。名前はカプチン修道会の服に由来します。' , image:File.open('app/assets/images/0_1.png') ,category: 0, display_order: 1)
Drink.create(name: 'エスプレッソ', word: '集中と活力', info: 'エスプレッソは濃厚で強いコーヒーで、イタリアが発祥。少量の水でコーヒー豆を高圧抽出する製法です。', image:File.open('app/assets/images/0_2.png') ,category: 0, display_order: 2)
Drink.create(name: 'モカ', word: '深い情熱と神秘の誘惑', info: 'モカはコーヒーの一種で、イエメンのモカ港から輸出された豆に由来します。チョコレート風味が特徴。' , image:File.open('app/assets/images/0_3.png') ,category: 0, display_order: 3)
Drink.create(name: 'チャイラテ', word: '温かな抱擁、スパイスの魔法' , info: 'チャイラテはインドの伝統的なマサラチャイにミルクを加えた飲み物。スパイスと紅茶の調和が特徴。', image:File.open('app/assets/images/0_4.png') ,category: 0, display_order: 4)
Drink.create(name: 'マキアート', word: '穏やかなひととき', info: 'エスプレッソに少量のミルクフォームを加えたイタリアのコーヒー。名前は「シミをつける」という意味。', image:File.open('app/assets/images/0_5.png') ,category: 0, display_order: 5)
Drink.create(name: 'カフェオレ', word: '和やかなひと時', info: 'コーヒーに同量のホットミルクを加えた飲み物。フランス発祥で、朝食に好まれる。' , image:File.open('app/assets/images/0_0.png') ,category: 0, display_order: 6)
Drink.create(name: 'カフェラテ', word: '穏やかなひと時', info: 'エスプレッソにスチームミルクを加えたイタリア発祥のコーヒー。優しい味わいが特徴です。' , image:File.open('app/assets/images/0_0.png') ,category: 0, display_order: 7)

Drink.create(name: 'コーラ', word:'若々しい活力' , info:'コーラは炭酸飲料の一種で、カフェインとカラメル色素を含む。1886年にアメリカで誕生し、世界中で愛されている。' , image:File.open('app/assets/images/2_0.png') ,category: 2, display_order: 0)
Drink.create(name: 'スプライト', word:'爽快な若さ' , info:'スプライトはレモンとライム風味の炭酸飲料で、1961年にコカ・コーラ社によって発売されました。' , image:File.open('app/assets/images/2_1.png') ,category: 2, display_order: 1)
Drink.create(name: 'ジンジャーエール', word:'活力と清涼' , info:'ジンジャーエールは、生姜の風味を持つ炭酸飲料です。消化を助ける効果があるとされ、リフレッシュに最適です。' , image:File.open('app/assets/images/2_2.png') ,category: 2, display_order: 2)
Drink.create(name: 'レモネード', word:'爽やかな始まり' , info:'レモン果汁、砂糖、水を混ぜた清涼飲料水。夏の暑い日にぴったりの飲み物で、ビタミンCが豊富。' , image:File.open('app/assets/images/2_3.png') ,category: 2, display_order: 3)
Drink.create(name: 'オレンジジュース', word:'活力と健康' , info:'ビタミンCが豊富で風邪予防に効果的。朝食の定番で、フレッシュな味わいが特徴。' , image:File.open('app/assets/images/2_4.png') ,category: 2, display_order: 4)
Drink.create(name: 'アップルジュース', word:'健康と純粋な喜び' , info:'アップルジュースはリンゴを搾った果汁で、ビタミンやミネラルが豊富。子供から大人まで幅広く愛されています。' , image:File.open('app/assets/images/2_5.png') ,category: 2, display_order: 5)
Drink.create(name: 'マンゴージュース', word:'熱帯の楽園' , info:'マンゴージュースは、甘くて濃厚な熱帯果実マンゴーを搾ったジュースです。ビタミン豊富で健康にも良いとされています。' , image:File.open('app/assets/images/2_6.png') ,category: 2, display_order: 6)
Drink.create(name: 'クランベリージュース', word:'活力と若々しさ' , info:'クランベリージュースは、鮮やかな赤色が特徴の果実ジュース。抗酸化作用が高く、尿路感染症の予防にも役立つとされています。' , image:File.open('app/assets/images/2_7.png') ,category: 2, display_order: 7)
Drink.create(name: 'トマトジュース', word:'活力と健康' , info:'トマトジュースは、リコピンやビタミンCが豊富で、美容と健康に良いとされる野菜ジュースです。' , image:File.open('app/assets/images/2_8.png') ,category: 2, display_order: 8)
Drink.create(name: 'パッションフルーツジュース', word:'情熱的な愛情' , info:'パッションフルーツジュースは、トロピカルな風味が特徴の果汁飲料です。南米原産で、名前の「パッション」は情熱ではなく、宣教師が花の形からキリストの受難を連想したことに由来します。' , image:File.open('app/assets/images/2_8.png') ,category: 2, display_order: 9)
Drink.create(name: 'グァバジュース', word:'健康と若さの秘訣' , info:'グァバジュースはビタミンCが豊富で、抗酸化作用があり、免疫力向上に効果的なトロピカルドリンクです。' , image:File.open('app/assets/images/2_9.png') ,category: 2, display_order: 10)
Drink.create(name: 'ココナッツウォーター', word:'自然の恵み、純粋なリフレッシュメント' , info:'ココナッツウォーターは、若いココナッツの中に含まれる透明な液体です。ミネラル豊富で、自然な甘みと爽やかさが特徴。' , image:File.open('app/assets/images/2_10.png') ,category: 2, display_order: 11)
Drink.create(name: 'タピオカミルクティー', word:'甘い時間、若さの象徴、楽しいひととき' , info:'台湾発祥のドリンクで、甘く煮たタピオカをミルクティーに入れたもの。若者を中心に世界的に人気。' , image:File.open('app/assets/images/2_11.png') ,category: 2, display_order: 12)
Drink.create(name: 'エルダーフラワージュース', word:'優雅な再生' , info:'エルダーフラワージュースは、エルダーの花から作られる甘く爽やかな飲み物です。健康や美容に良いとされています。' , image:File.open('app/assets/images/2_12.png') ,category: 2, display_order: 13)
Drink.create(name: 'レッドブル', word:' 活力の泉' , info:'レッドブルはエナジードリンクの一種で、疲労回復や集中力向上を目的として世界中で愛飲されています。' , image:File.open('app/assets/images/2_13.png') ,category: 2, display_order: 14)
Drink.create(name: 'ミネラルウォーター', word:'自然の恵み、生命の源' , info:'地下水や湧水に含まれるミネラル分を含んだ水。健康や美容に良いとされ、多くの人に愛飲されています。' , image:File.open('app/assets/images/2_14.png') ,category: 2, display_order: 15)

Drink.create(name: 'シャーリーテンプル', word:'純真な喜び' , info:'ノンアルコールカクテルで、子役スターのシャーリー・テンプルにちなんで名付けられました。グレナデンシロップとジンジャーエールを使います。' , image:File.open('app/assets/images/4_0.png') ,category: 4, display_order: 0)
Drink.create(name: 'フルーツパンチ', word:'祝祭の喜び' , info:'フルーツパンチは、様々なフルーツジュースを混ぜ合わせたパーティードリンクです。由来はインドの「パンチ」から。' , image:File.open('app/assets/images/4_2.png') ,category: 4, display_order: 2)
Drink.create(name: 'ベリー2', word:'甘酸っぱい青春の味' , info:'ベリー2は、ベリー類のフルーツジュースをミックスしたノンアルコールカクテルです。フレッシュで爽やかな味わいが特徴。' , image:File.open('app/assets/images/4_3.png') ,category: 4, display_order: 3)
Drink.create(name: 'フロリダ', word:'太陽の輝き' , info:'フロリダは、オレンジジュースをベースにしたカクテルで、ビタミン豊富な朝の一杯として人気があります。' , image:File.open('app/assets/images/4_4.png') ,category: 4, display_order: 4)
Drink.create(name: 'ピンクパンサー', word:'愛らしい冒険心' , info:'ピンクパンサーは、その鮮やかなピンク色から名付けられたカクテルです。フルーティーで甘い味わいが特徴。' , image:File.open('app/assets/images/4_5.png') ,category: 4, display_order: 5)
Drink.create(name: 'サンセットクーラー', word:'夕焼けの誘い' , info:'サンセットクーラーは、オレンジジュースとグレナデンシロップを使ったカクテル。夕日のようなグラデーションが特徴です。' , image:File.open('app/assets/images/4_6.png') ,category: 4, display_order: 6)

Drink.create(name: 'モヒート', word:'爽快な休息' , info:'モヒートはラムベースのカクテルで、ミント、ライム、砂糖、ソーダ水を合わせたキューバ発祥の飲み物です。' , image:File.open('app/assets/images/5_0.png') ,category: 5, display_order: 0)
Drink.create(name: 'マティーニ', word:'洗練されたエレガンス' , info:'マティーニはジンとベルモットをベースにしたカクテル。ジェームズ・ボンドの「シェイクン、ノット・スタード」で有名。' , image:File.open('app/assets/images/5_1.png') ,category: 5, display_order: 1)
Drink.create(name: 'ダイキリ', word:'爽快な自由' , info:'ラムベースのカクテルで、ライムジュースとシュガーシロップを加えて作ります。キューバ発祥のカクテルです。' , image:File.open('app/assets/images/5_2.png') ,category: 5, display_order: 2)
Drink.create(name: 'ミモザ', word:'爽やかな始まり' , info:'ミモザは、オレンジジュースとシャンパンを混ぜたカクテルです。名前は黄色いミモザの花から来ており、ブランチの定番です。' , image:File.open('app/assets/images/5_3.png') ,category: 5, display_order: 3)
Drink.create(name: 'ベリーニ', word:'華やかな始まり' , info:'ベリーニは、白桃のピューレとプロセッコを合わせたイタリア発祥のカクテルです。1948年にヴェネツィアで誕生しました。' , image:File.open('app/assets/images/5_4.png') ,category: 5, display_order: 4)
Drink.create(name: 'バーバラ', word:'神秘的な魅力' , info:'バーバラは、ウォッカをベースにしたカクテルで、フルーティーな味わいが特徴です。由来は不明ですが、その名前から神秘的なイメージを持つ人も多いでしょう。' , image:File.open('app/assets/images/5_5.png') ,category: 5, display_order: 5)
Drink.create(name: 'チャイナブルー', word:'神秘的な夜の誘惑' , info:'チャイナブルーは、ライチリキュールとブルーキュラソーをベースにしたカクテル。爽やかな甘さと鮮やかな青色が特徴です。' , image:File.open('app/assets/images/5_6.png') ,category: 5, display_order: 6)
Drink.create(name: 'ファジーネーブル', word:'ほんわかした友情' , info:'ファジーネーブルは、桃のリキュール（ピーチツリー）とオレンジジュースをベースにしたカクテル。名前の由来は「もじゃもじゃしたオレンジ」。' , image:File.open('app/assets/images/5_7.png') ,category: 5, display_order: 7)
Drink.create(name: 'スクリュードライバー', word:'活力と創造性' , info:'ウォッカとオレンジジュースを混ぜたカクテル。名前の由来は工具を使って混ぜたことから。' , image:File.open('app/assets/images/5_8.png') ,category: 5, display_order: 8)
Drink.create(name: 'カーディナル', word:'洗練された魅力' , info:'カーディナルは、赤ワインとカシスリキュールをベースにしたカクテル。エレガントな味わいが特徴です。' , image:File.open('app/assets/images/5_9.png') ,category: 5, display_order: 9)
Drink.create(name: 'ドッグズノーズ', word:'親密な絆' , info:'ドッグズノーズはビールにジンを加えたイギリスの伝統的なカクテルです。親しい仲間との団欒を象徴する飲み物。' , image:File.open('app/assets/images/5_10.png') ,category: 5, display_order: 10)
Drink.create(name: 'X.Y.Z', word:'未知の可能性' , info:'ラム酒をベースに、オレンジリキュールであるキュラソーとレモンジュースを加えたカクテルのことです。' , image:File.open('app/assets/images/5_11.png') ,category: 5, display_order: 11)
Drink.create(name: 'チャーリーチャップリン', word:'静かなる喜びの時' , info:'スロー・ジン、アプリコット・ブランデー、ライムジュースを使用したカクテル。サイレント映画の巨匠にちなんで名付けられました。' , image:File.open('app/assets/images/5_12.png') ,category: 5, display_order: 12)
Drink.create(name: 'ブラッディメアリー', word:'情熱と再生' , info:'トマトジュースとウォッカをベースに、レモン汁、タバスコ、ウスターソースで味付けされるカクテル。1920年代に誕生したとされる。' , image:File.open('app/assets/images/5_13.png') ,category: 5, display_order: 13)

Drink.create(name: 'ジャックダニエルズ', word:'不屈の精神' , info:'ジャックダニエルズはテネシー州で製造されるアメリカンウイスキー。独特のフィルタリング方法「チャコール・メローイング」で知られる。' , image:File.open('app/assets/images/6_0.png') ,category: 6, display_order: 0)
Drink.create(name: 'タリスカー', word:' 荒波を越える勇気' , info:'タリスカーはスコットランドのスカイ島にある蒸留所で作られるシングルモルトウイスキーです。ピートの香りと海の風味が特徴。' , image:File.open('app/assets/images/6_1.png') ,category: 6, display_order: 1)
Drink.create(name: 'マッカラン12年', word:'深遠なる時の熟成' , info:'マッカラン12年は、スコットランドのスペイサイド地方で製造されるシングルモルトスコッチウイスキーです。12年間の樽熟成により、豊かな味わいと複雑な香りが特徴です。' , image:File.open('app/assets/images/6_2.png') ,category: 6, display_order: 2)
Drink.create(name: 'グレンリベット12年', word:'伝統の洗練' , info:'スコットランドのスペイサイド地方で生産されるシングルモルトスコッチウイスキー。滑らかでフルーティな味わいが特徴。' , image:File.open('app/assets/images/6_3.png') ,category: 6, display_order: 3)
Drink.create(name: '山崎12年', word:'熟成された時の贈り物' , info:'山崎12年はサントリーが製造するプレミアムシングルモルトウイスキー。繊細かつ豊かな香りと味わいが特徴。' , image:File.open('app/assets/images/6_4.png') ,category: 6, display_order: 4)
Drink.create(name: 'ブッカーズ', word:'本物の追求' , info:'ブッカーズはバーボンの一種で、バーボンの父とも呼ばれるブッカー・ノーが作り出した、手付かずのカスクストレングスウイスキーです。' , image:File.open('app/assets/images/6_5.png') ,category: 6, display_order: 5)
Drink.create(name: 'ジェームソン', word:'伝統の絆' , info:'ジェームソンはアイリッシュウイスキーの代表的なブランドで、1780年にジョン・ジェームソンによって創業されました。' , image:File.open('app/assets/images/6_6.png') ,category: 6, display_order: 6)
Drink.create(name: 'アードベッグ10年', word:'深遠なる謎' , info:'アードベッグ10年は、スコットランドのアイラ島で製造されるシングルモルトウイスキー。ピートの強い燻製香が特徴。' , image:File.open('app/assets/images/6_7.png') ,category: 6, display_order: 7)
Drink.create(name: 'アラン10年', word:'未知なる旅への第一歩' , info:' アラン10年は、スコットランドのアラン島で製造されるシングルモルトウイスキー。独特のフルーティさとスパイスが特徴。' , image:File.open('app/assets/images/6_8.png') ,category: 6, display_order: 8)
Drink.create(name: 'グレンモーレンジィ', word:'静かなる瞑想' , info:'グレンモーレンジィはスコットランドのハイランド地方で製造されるシングルモルトウイスキーです。繊細でフルーティーな味わいが特徴。' , image:File.open('app/assets/images/6_9.png') ,category: 6, display_order: 9)


#Drink.create(name: 'アサヒスーパードライ', word:'刷新の風' , info:'アサヒスーパードライは1987年に発売された日本のビール。キレのある爽快な味わいが特徴で、国内外で人気を博しています。' , image:File.open('') ,category: 9, display_order: 0)
#Drink.create(name: 'サッポロ黒ラベル', word:'洗練された夜の始まり' , info:'サッポロ黒ラベルは、サッポロビール株式会社が製造する日本のビール。バランスの良い味わいが特徴です。' , image:File.open('') ,category: 9, display_order: 1)
#Drink.create(name: 'キリン一番絞り', word:'始まりの一歩' , info:'キリン一番絞りは、キリンビール株式会社が製造するビールで、一番搾り製法による爽やかな味わいが特徴です。' , image:File.open('') ,category: 9, display_order: 2)
#Drink.create(name: 'ザ・プレミアム・モルツ', word:'至高のひととき' , info:'サントリーが製造する高級ビール。厳選された麦芽とホップを使用し、コクと香りが特徴です。' , image:File.open('') ,category: 9, display_order: 3)
#Drink.create(name: 'エビス', word:'繁栄と喜びの時' , info:'エビスビールは日本の老舗ビールブランドで、ヱビスビールとも表記されます。サッポロビールが製造し、濃厚でコクのある味わいが特徴です。' , image:File.open('') ,category: 9, display_order: 4)
#Drink.create(name: 'バドワイザー', word:'友情の絆' , info:'バドワイザーはアメリカのアンハイザー・ブッシュ社が製造するラガービール。1876年に誕生し、世界的に有名なビールブランドです。' , image:File.open('') ,category: 9, display_order: 5)
#Drink.create(name: 'ギネス', word:'深遠なる伝統' , info:'ギネスはアイルランド発祥の有名な黒ビールで、独特のクリーミーな泡と芳醇な味わいが特徴です。' , image:File.open('') ,category: 9, display_order: 6)
#Drink.create(name: 'ハイネケン', word:'世界を繋ぐ友情' , info:'ハイネケンはオランダ発祥の国際的なビールブランド。1864年に創業し、特徴的な緑色のボトルが有名です。' , image:File.open('') ,category: 9, display_order: 7)
#Drink.create(name: 'コロナ', word:'太陽の下での解放感' , info:'コロナはメキシコのビールブランドで、ライムを挿して飲むのが特徴的な爽やかなラガービールです。' , image:File.open('') ,category: 9, display_order: 8)
#Drink.create(name: 'ヒューガルデンホワイト', word:'神秘的なひととき' , info:'ベルギー発のホワイトビール。オレンジピールとコリアンダーシードを使用し、爽やかな味わいが特徴。' , image:File.open('') ,category: 9, display_order: 9)
