# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Drink.create(name: "コーヒー", category: "カフェ", display_order: 0)
Drink.create(name: "カプチーノ", category: "カフェ", display_order: 1)
Drink.create(name: "エスプレッソ", category: "カフェ", display_order: 2)
Drink.create(name: "モカ", category: "カフェ", display_order: 3)
Drink.create(name: "チャイラテ", category: "カフェ", display_order: 4)
Drink.create(name: "マキアート", category: "カフェ", display_order: 5)
Drink.create(name: "カフェオレ", category: "カフェ", display_order: 6)
Drink.create(name: "カフェラテ", category: "カフェ", display_order: 7)

Drink.create(name: "ハワイ・コナ", category: "コーヒー豆", display_order: 0)
Drink.create(name: "エチオピア・モカ", category: "コーヒー豆", display_order: 1)
Drink.create(name: "コスタリカ", category: "コーヒー豆", display_order: 2)
Drink.create(name: "ジャマイカ・ブルーマウンテン", category: "コーヒー豆", display_order: 3)
Drink.create(name: "パナマ・ゲイシャ", category: "コーヒー豆", display_order: 4)
Drink.create(name: "タンザニア・キリマンジャイロ", category: "コーヒー豆", display_order: 5)
Drink.create(name: "コロンビア・エメラルドマウンテン", category: "コーヒー豆", display_order: 6)
Drink.create(name: "インドネシア・マンデリン", category: "コーヒー豆", display_order: 7)

Drink.create(name: "コーラ", category: "ソフトドリンク", display_order: 0)
Drink.create(name: "スプライト", category: "ソフトドリンク", display_order: 1)
Drink.create(name: "ジンジャーエール", category: "ソフトドリンク", display_order: 2)
Drink.create(name: "レモネード", category: "ソフトドリンク", display_order: 3)
Drink.create(name: "オレンジジュース", category: "ソフトドリンク", display_order: 4)
Drink.create(name: "アップルジュース", category: "ソフトドリンク", display_order: 5)
Drink.create(name: "マンゴージュース", category: "ソフトドリンク", display_order: 6)
Drink.create(name: "クランベリージュース", category: "ソフトドリンク", display_order: 7)
Drink.create(name: "トマトジュース", category: "ソフトドリンク", display_order: 8)
Drink.create(name: "パッションフルーツジュース", category: "ソフトドリンク", display_order: 9)
Drink.create(name: "グァバジュース", category: "ソフトドリンク", display_order: 10)
Drink.create(name: "ココナッツウォーター", category: "ソフトドリンク", display_order: 11)
Drink.create(name: "タピオカミルクティー", category: "ソフトドリンク", display_order: 12)
Drink.create(name: "エルダーフラワージュース", category: "ソフトドリンク", display_order: 13)
Drink.create(name: "レッドブル", category: "ソフトドリンク", display_order: 14)
Drink.create(name: "ミネラルウォーター", category: "ソフトドリンク", display_order: 15)

Drink.create(name: "アールグレイティー", category: "お茶", display_order: 0)
Drink.create(name: "ダージリンティー", category: "お茶", display_order: 1)
Drink.create(name: "アッサムティー", category: "お茶", display_order: 2)
Drink.create(name: "ジャスミンティー", category: "お茶", display_order: 3)
Drink.create(name: "カモミールティー", category: "お茶", display_order: 4)
Drink.create(name: "ペパーミントティー", category: "お茶", display_order: 5)
Drink.create(name: "ルイボスティー", category: "お茶", display_order: 6)
Drink.create(name: "レモングラスティー", category: "お茶", display_order: 7)
Drink.create(name: "ラベンダーティー", category: "お茶", display_order: 8)
Drink.create(name: "セイロンティー", category: "お茶", display_order: 9)
Drink.create(name: "烏龍茶", category: "お茶", display_order: 10)
Drink.create(name: "プーアール茶", category: "お茶", display_order: 11)
Drink.create(name: "抹茶", category: "お茶", display_order: 12)
Drink.create(name: "ほうじ茶", category: "お茶", display_order: 13)

Drink.create(name: "シャーリーテンプル", category: "ノンアルコールカクテル", display_order: 0)
Drink.create(name: "シンデレラ", category: "ノンアルコールカクテル", display_order: 1)
Drink.create(name: "フルーツパンチ", category: "ノンアルコールカクテル", display_order: 2)
Drink.create(name: "ベリー2", category: "ノンアルコールカクテル", display_order: 3)
Drink.create(name: "フロリダ", category: "ノンアルコールカクテル", display_order: 4)
Drink.create(name: "ピンクパンサー", category: "ノンアルコールカクテル", display_order: 5)
Drink.create(name: "サンセットクーラー", category: "ノンアルコールカクテル", display_order: 6)

Drink.create(name: "モヒート", category: "カクテル", display_order: 0)
Drink.create(name: "マティーニ", category: "カクテル", display_order: 1)
Drink.create(name: "ダイキリ", category: "カクテル", display_order: 2)
Drink.create(name: "ミモザ", category: "カクテル", display_order: 3)
Drink.create(name: "ベリーニ", category: "カクテル", display_order: 4)
Drink.create(name: "バーバラ", category: "カクテル", display_order: 5)
Drink.create(name: "チャイナブルー", category: "カクテル", display_order: 6)
Drink.create(name: "ファジーネーブル", category: "カクテル", display_order: 7)
Drink.create(name: "スクリュードライバー", category: "カクテル", display_order: 8)
Drink.create(name: "カーディナル", category: "カクテル", display_order: 9)
Drink.create(name: "ドッグズノーズ", category: "カクテル", display_order: 10)
Drink.create(name: "X.Y.Z", category: "カクテル", display_order: 11)
Drink.create(name: "チャーリーチャップリン", category: "カクテル", display_order: 12)
Drink.create(name: "ブラッディメアリー", category: "カクテル", display_order: 13)

Drink.create(name: "ジャックダニエルズ", category: "ウイスキー", display_order: 0)
Drink.create(name: "タリスカー", category: "ウイスキー", display_order: 1)
Drink.create(name: "マッカラン12年", category: "ウイスキー", display_order: 2)
Drink.create(name: "グレンリベット12年", category: "ウイスキー", display_order: 3)
Drink.create(name: "山崎12年", category: "ウイスキー", display_order: 4)
Drink.create(name: "ブッカーズ", category: "ウイスキー", display_order: 5)
Drink.create(name: "ジェームソン", category: "ウイスキー", display_order: 6)
Drink.create(name: "アードベッグ10年", category: "ウイスキー", display_order: 7)
Drink.create(name: "アラン10年", category: "ウイスキー", display_order: 8)
Drink.create(name: "グレンモーレンジィ", category: "ウイスキー", display_order: 9)

Drink.create(name: "獺祭(だっさい)", category: "日本酒", display_order: 0)
Drink.create(name: "而今(じこん)", category: "日本酒", display_order: 1)
Drink.create(name: "東洋美人", category: "日本酒", display_order: 2)
Drink.create(name: "久保田", category: "日本酒", display_order: 3)
Drink.create(name: "寫樂(しゃらく)", category: "日本酒", display_order: 4)
Drink.create(name: "No.6", category: "日本酒", display_order: 5)
Drink.create(name: "亜麻猫(あまねこ)", category: "日本酒", display_order: 6)
Drink.create(name: "くどき上手", category: "日本酒", display_order: 7)
Drink.create(name: "十四代", category: "日本酒", display_order: 8)
Drink.create(name: "どぶろく", category: "日本酒", display_order: 9)

Drink.create(name: "リースリング", category: "ワイン", display_order: 0)
Drink.create(name: "シャルドネ", category: "ワイン", display_order: 1)
Drink.create(name: "ソーヴィニヨン・ブラン", category: "ワイン", display_order: 2)
Drink.create(name: "カベルネ・ソーヴィニョン", category: "ワイン", display_order: 3)
Drink.create(name: "セミヨン", category: "ワイン", display_order: 4)
Drink.create(name: "甲州", category: "ワイン", display_order: 5)
Drink.create(name: "ピノ・ノワール", category: "ワイン", display_order: 6)
Drink.create(name: "シラー", category: "ワイン", display_order: 7)
Drink.create(name: "メルロー", category: "ワイン", display_order: 8)
Drink.create(name: "グルナッシュ", category: "ワイン", display_order: 9)

Drink.create(name: "アサヒスーパードライ", category: "ビール", display_order: 0)
Drink.create(name: "サッポロ黒ラベル", category: "ビール", display_order: 1)
Drink.create(name: "キリン一番絞り", category: "ビール", display_order: 2)
Drink.create(name: "ザ・プレミアム・モルツ", category: "ビール", display_order: 3)
Drink.create(name: "エビス", category: "ビール", display_order: 4)
Drink.create(name: "バドワイザー", category: "ビール", display_order: 5)
Drink.create(name: "ギネス", category: "ビール", display_order: 6)
Drink.create(name: "ハイネケン", category: "ビール", display_order: 7)
Drink.create(name: "コロナ", category: "ビール", display_order: 8)
Drink.create(name: "ヒューガルデンホワイト", category: "ビール", display_order: 9)
