# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Drink.create(name: "コーヒー", category: 0, display_order: 0)
Drink.create(name: "カプチーノ", category: 0, display_order: 1)
Drink.create(name: "エスプレッソ", category: 0, display_order: 2)
Drink.create(name: "モカ", category: 0, display_order: 3)
Drink.create(name: "チャイラテ", category: 0, display_order: 4)
Drink.create(name: "マキアート", category: 0, display_order: 5)
Drink.create(name: "カフェオレ", category: 0, display_order: 6)
Drink.create(name: "カフェラテ", category: 0, display_order: 7)

Drink.create(name: "ハワイ・コナ", category: 1, display_order: 0)
Drink.create(name: "エチオピア・モカ", category: 1, display_order: 1)
Drink.create(name: "コスタリカ", category: 1, display_order: 2)
Drink.create(name: "ジャマイカ・ブルーマウンテン", category: 1, display_order: 3)
Drink.create(name: "パナマ・ゲイシャ", category: 1, display_order: 4)
Drink.create(name: "タンザニア・キリマンジャイロ", category: 1, display_order: 5)
Drink.create(name: "コロンビア・エメラルドマウンテン", category: 1, display_order: 6)
Drink.create(name: "インドネシア・マンデリン", category: 1, display_order: 7)

Drink.create(name: "コーラ", category: 2, display_order: 0)
Drink.create(name: "スプライト", category: 2, display_order: 1)
Drink.create(name: "ジンジャーエール", category: 2, display_order: 2)
Drink.create(name: "レモネード", category: 2, display_order: 3)
Drink.create(name: "オレンジジュース", category: 2, display_order: 4)
Drink.create(name: "アップルジュース", category: 2, display_order: 5)
Drink.create(name: "マンゴージュース", category: 2, display_order: 6)
Drink.create(name: "クランベリージュース", category: 2, display_order: 7)
Drink.create(name: "トマトジュース", category: 2, display_order: 8)
Drink.create(name: "パッションフルーツジュース", category: 2, display_order: 9)
Drink.create(name: "グァバジュース", category: 2, display_order: 10)
Drink.create(name: "ココナッツウォーター", category: 2, display_order: 11)
Drink.create(name: "タピオカミルクティー", category: 2, display_order: 12)
Drink.create(name: "エルダーフラワージュース", category: 2, display_order: 13)
Drink.create(name: "レッドブル", category: 2, display_order: 14)
Drink.create(name: "ミネラルウォーター", category: 2, display_order: 15)

Drink.create(name: "アールグレイティー", category: 3, display_order: 0)
Drink.create(name: "ダージリンティー", category: 3, display_order: 1)
Drink.create(name: "アッサムティー", category: 3, display_order: 2)
Drink.create(name: "ジャスミンティー", category: 3, display_order: 3)
Drink.create(name: "カモミールティー", category: 3, display_order: 4)
Drink.create(name: "ペパーミントティー", category: 3, display_order: 5)
Drink.create(name: "ルイボスティー", category: 3, display_order: 6)
Drink.create(name: "レモングラスティー", category: 3, display_order: 7)
Drink.create(name: "ラベンダーティー", category: 3, display_order: 8)
Drink.create(name: "セイロンティー", category: 3, display_order: 9)
Drink.create(name: "烏龍茶", category: 3, display_order: 10)
Drink.create(name: "プーアール茶", category: 3, display_order: 11)
Drink.create(name: "抹茶", category: 3, display_order: 12)
Drink.create(name: "ほうじ茶", category: 3, display_order: 13)

Drink.create(name: "シャーリーテンプル", category: 4, display_order: 0)
Drink.create(name: "シンデレラ", category: 4, display_order: 1)
Drink.create(name: "フルーツパンチ", category: 4, display_order: 2)
Drink.create(name: "ベリー2", category: 4, display_order: 3)
Drink.create(name: "フロリダ", category: 4, display_order: 4)
Drink.create(name: "ピンクパンサー", category: 4, display_order: 5)
Drink.create(name: "サンセットクーラー", category: 4, display_order: 6)

Drink.create(name: "モヒート", category: 5, display_order: 0)
Drink.create(name: "マティーニ", category: 5, display_order: 1)
Drink.create(name: "ダイキリ", category: 5, display_order: 2)
Drink.create(name: "ミモザ", category: 5, display_order: 3)
Drink.create(name: "ベリーニ", category: 5, display_order: 4)
Drink.create(name: "バーバラ", category: 5, display_order: 5)
Drink.create(name: "チャイナブルー", category: 5, display_order: 6)
Drink.create(name: "ファジーネーブル", category: 5, display_order: 7)
Drink.create(name: "スクリュードライバー", category: 5, display_order: 8)
Drink.create(name: "カーディナル", category: 5, display_order: 9)
Drink.create(name: "ドッグズノーズ", category: 5, display_order: 10)
Drink.create(name: "X.Y.Z", category: 5, display_order: 11)
Drink.create(name: "チャーリーチャップリン", category: 5, display_order: 12)
Drink.create(name: "ブラッディメアリー", category: 5, display_order: 13)

Drink.create(name: "ジャックダニエルズ", category: 6, display_order: 0)
Drink.create(name: "タリスカー", category: 6, display_order: 1)
Drink.create(name: "マッカラン12年", category: 6, display_order: 2)
Drink.create(name: "グレンリベット12年", category: 6, display_order: 3)
Drink.create(name: "山崎12年", category: 6, display_order: 4)
Drink.create(name: "ブッカーズ", category: 6, display_order: 5)
Drink.create(name: "ジェームソン", category: 6, display_order: 6)
Drink.create(name: "アードベッグ10年", category: 6, display_order: 7)
Drink.create(name: "アラン10年", category: 6, display_order: 8)
Drink.create(name: "グレンモーレンジィ", category: 6, display_order: 9)

Drink.create(name: "獺祭(だっさい)", category: 7, display_order: 0)
Drink.create(name: "而今(じこん)", category: 7, display_order: 1)
Drink.create(name: "東洋美人", category: 7, display_order: 2)
Drink.create(name: "久保田", category: 7, display_order: 3)
Drink.create(name: "寫樂(しゃらく)", category: 7, display_order: 4)
Drink.create(name: "No.6", category: 7, display_order: 5)
Drink.create(name: "亜麻猫(あまねこ)", category: 7, display_order: 6)
Drink.create(name: "くどき上手", category: 7, display_order: 7)
Drink.create(name: "十四代", category: 7, display_order: 8)
Drink.create(name: "どぶろく", category: 7, display_order: 9)

Drink.create(name: "リースリング", category: 8, display_order: 0)
Drink.create(name: "シャルドネ", category: 8, display_order: 1)
Drink.create(name: "ソーヴィニヨン・ブラン", category: 8, display_order: 2)
Drink.create(name: "カベルネ・ソーヴィニョン", category: 8, display_order: 3)
Drink.create(name: "セミヨン", category: 8, display_order: 4)
Drink.create(name: "甲州", category: 8, display_order: 5)
Drink.create(name: "ピノ・ノワール", category: 8, display_order: 6)
Drink.create(name: "シラー", category: 8, display_order: 7)
Drink.create(name: "メルロー", category: 8, display_order: 8)
Drink.create(name: "グルナッシュ", category: 8, display_order: 9)

Drink.create(name: "アサヒスーパードライ", category: 9, display_order: 0)
Drink.create(name: "サッポロ黒ラベル", category: 9, display_order: 1)
Drink.create(name: "キリン一番絞り", category: 9, display_order: 2)
Drink.create(name: "ザ・プレミアム・モルツ", category: 9, display_order: 3)
Drink.create(name: "エビス", category: 9, display_order: 4)
Drink.create(name: "バドワイザー", category: 9, display_order: 5)
Drink.create(name: "ギネス", category: 9, display_order: 6)
Drink.create(name: "ハイネケン", category: 9, display_order: 7)
Drink.create(name: "コロナ", category: 9, display_order: 8)
Drink.create(name: "ヒューガルデンホワイト", category: 9, display_order: 9)
